version: 0.0
os: linux
files:
  - source: target/ROOT.war
    destination: /usr/local/tomcat9/webapps/
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root